
language: python
python:
  - 3.7
cache: pypi

install:
  - pip install flake8 

script:
  - python -m flake8 VR/
  - pytest VR/test_auth.py/

after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - master


