
language: python
python:
  - 3.7
cache: pypi

install:
  - pip install flake8 codecov pytest pytest-cov
  - pip install scipy


script:
  - flake8 --exclude=*.py
  - coverage run -m pytest 

after_success:
  - codecov
branches:
  only:
  - master
