
language: python
python:
  - 3.7
cache: pypi

install:
  - pip install flake8
  - pip install flake8 codecov pytest pytest-cov
  - pip install coverage


script:
  - python -m flake8 VR/
  - cd VR
  - python -m pytest test_auth.py --cov VR/

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
branches:
  only:
  - master


