
language: python
python:
  - 3.7
cache: pypi

install:
  - echo "no dependencies"

script:
  - pytest VR/test_auth.py/

after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - master


